
<?php 
$id = (int)$this->getRequest()->getParam('id');//var_dump($id);
$data = Mage::getModel('s/s')->load($id)->getData();
$msg = (int)$this->getRequest()->getParam('msg');
if(!is_null($data['date']))
{
    $data['date'] = date('m/j/Y', strtotime($data['date']));
}
?>
<?php /*if($msg==1){?>
<div id="messages_product_view" style="font-weight: bold;text-align: center;color:green">Record saved succesfully</div>
<?php }*/ ?>
<div class="page-title">
    <h1><?php echo __('Special Order') ?></h1>
</div>
<div class="border-wrapper">
<form action="<?php echo Mage::getUrl('s/index/post', array('id'=>$id)); ?>" id="specialorderForm" method="post" AUTOCOMPLETE=OFF>
    <div class="fieldset">
        <h2 class="legend"><?php echo __('Order Information') ?></h2>
        <ul class="form-list">
         
                <label for="content" class="required"><em>*</em><?php echo __('Product Description') ?></label>
                <div class="input-box">
                    <textarea name="content" id="content" AUTOCOMPLETE=OFF style="width:485px" class="required-entry input-text" cols="3" rows="3"><?php echo $data['content']?></textarea>
                </div>
           
        
                <label><?php echo __('URL') ?></label>
                <div class="input-box">
                    <input type="text" name="url" value="<?php echo $data['url']?>" id="url" maxlength="500" size="50"/>
                   <span id ="result" style="color: #F60;float: right;margin-right: -73px;margin-top: -18px;"></span> 
                </div>
         
      
                <label><?php echo __('Price') ?></label>
                <div class="input-box" style="margin-left:-89px">
                    <input type="text"  name="price" value="<?php echo $data['price']?>"  id="price" maxlength="12" size="12" onkeypress="return isNumberKey(event)"/>
                </div>
        
    
                <label ><?php echo __('Date') ?></label>
                <div class="input-box range-line date" style="margin-left:-85px">
                    <input type="text" name="date" value="<?php echo $data['date']?>"  id="date" maxlength="10" size="10"/>
                <img id="date_img" class="v-middle" title="Date selector" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>"></div>
     
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo __('* Required Fields') ?></p>

        <button type="submit" name="update" id="update" value="1" title="<?php echo __('Send') ?>" class="button"><span><span><?php echo __('Save') ?></span></span></button>
       <button type="button" name="back" id="back" onclick="window.location='<?php echo $this->getUrl('s/index/index');?>'" value="1" title="<?php echo __('Send') ?>" class="button"><span><span><?php echo __('Back') ?></span></span></button>
    </div>
    
</form>
<script type="text/javascript">
//<![CDATA[
  Calendar.setup({
        inputField : 'date',
        ifFormat : '%m/%e/%Y',
        button : 'date_img',
        align : 'Bl',
        singleClick : true
    });
	
 enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
Calendar._am = "AM"; // am/pm
Calendar._pm = "PM";

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "About the calendar";

Calendar._TT["ABOUT"] =
"DHTML Date/Time Selector\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
"\n\n" +
"Date selection:\n" +
"- Use the \xab, \xbb buttons to select year\n" +
"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
"- Hold mouse button on any of the above buttons for faster selection.";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"Time selection:\n" +
"- Click on any of the time parts to increase it\n" +
"- or Shift-click to decrease it\n" +
"- or click and drag for faster selection.";

Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
Calendar._TT["GO_TODAY"] = "Go Today";
Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
Calendar._TT["SEL_DATE"] = "Select date";
Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';

// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "Display %s first";

// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = "0,6";

Calendar._TT["CLOSE"] = "Close";
Calendar._TT["TODAY"] = "Today";
Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";

Calendar._TT["WK"] = "Week";
Calendar._TT["TIME"] = "Time:";

CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = -28800;
CalendarDateObject._SERVER_TIMZEONE_SECONDS = 1333496531;

    var contactForm = new VarienForm('specialorderForm', true);
	
	 function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

         return true;
      }
	 // var $j = jQuery.noConflict(); 
	 
 function validateURL(textval) {
      var urlregex = new RegExp( "^(http|https|ftp)\://([a-zA-Z0-9\.\-]+(\:[a-zA-Z0-9\.&amp;%\$\-]+)*@)*((25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9])\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0)\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0)\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[0-9])|([a-zA-Z0-9\-]+\.)*[a-zA-Z0-9\-]+\.(com|edu|gov|int|mil|net|org|biz|arpa|info|name|pro|aero|coop|museum|[a-zA-Z]{2}))(\:[0-9]+)*(/($|[a-zA-Z0-9\.\,\?\'\\\+&amp;%\$#\=~_\-]+))*$");

  return urlregex.test(textval);
}


jQuery(document).ready(function() {
	//alert("sasdas");
	//$("#price").attr("style","text-align:right;");
 jQuery('#price').css('text-align', 'right');
     jQuery("#url").bind('blur',function ()
        {
			
            if(validateURL(jQuery(this).val())){
				//alert("khan");
                jQuery('#result').html('Valid URL')          
            }
            else{
				//alert("asasd");
                jQuery('#result').html('Invalid URL');
				 jQuery('#url').val('');
				 jQuery('#url').focus();
            }
        }    
    )

 

});

//]]>
</script>
</div>