<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>
<div class="jm-info clearfix">
  <?php echo $this->getChildHtml() ?>
</div>
<div class="jm-legal">
	<?php echo $this->getCopyright() ?>
<?php /*?>Powered by test <a href="http://www.joomlart.com/magento/themes/jm-megamall" title="JM MegaMall" rel="nofollow">JM MegaMall</a> - Designed by JoomlArt.com<?php */?>
</div>
